/* eslint-env node */
/**
 * Generates src/appVersion.ts from package.json's "version" so the running app
 * can display the exact version that gets deployed. Runs as part of `build-web`
 * (and from the deploy script), keeping the app and the deployed bundle in sync
 * automatically — package.json stays the single source of truth.
 */
const path = require("path");
const fs = require("fs");

const PROJECT_ROOT = path.resolve(__dirname, "..");
const { version } = require(path.join(PROJECT_ROOT, "package.json"));
const OUT = path.join(PROJECT_ROOT, "src", "appVersion.ts");

const contents = `// AUTO-GENERATED by scripts/gen-version.js — do not edit by hand.
// Sourced from package.json "version"; bumped on deploy.
export const APP_VERSION = "${version}";
`;

fs.writeFileSync(OUT, contents);
console.log(`appVersion.ts -> ${version}`);
